---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: agn-source-code
  - name: dependency-cache
outputs:
  - name: agn-qa

run:
  path: /bin/sh
  args: ["agn-source-code/ci/scripts/build-qa.sh"]
  #path:  agn-ui/ci/scripts/build.sh

  
